INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (1 km/h)', 0.027); -- (9.8 / (60 * 8))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (2 km/h)', 0.054); -- (9.8 / (60 * 4))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (3 km/h)', 0.081); -- (9.8 / (60 * (8/3)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (4 km/h)', 0.109); -- (9.8 / (60 * 2))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (5 km/h)', 0.137); -- (9.8 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (6 km/h)', 0.164); -- (9.8 / (60 * (8/6)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (7 km/h)', 0.191); -- (9.8 / (60 * (8/7)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (8 km/h)', 0.218); -- (9.8 / (60 * (8/8)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (9 km/h)', 0.245); -- (9.8 / (60 * (8/9)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (10 km/h)', 0.273); -- (9.8 / (60 * (8/10)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (11 km/h)', 0.300); -- (9.8 / (60 * (8/11)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (12 km/h)', 0.327); -- (9.8 / (60 * (8/12)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (13 km/h)', 0.354); -- (9.8 / (60 * (8/13)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (14 km/h)', 0.381); -- (9.8 / (60 * (8/14)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Correr (15 km/h)', 0.408); -- (9.8 / (60 * (8/15)))


INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (1 km/h)', 0.012); -- (3.8 / (60 * 5))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (2 km/h)', 0.025); -- (3.8 / (60 * 2.5))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (3 km/h)', 0.038); -- (3.8 / (60 * (5/3)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (4 km/h)', 0.051); -- (3.8 / (60 * 1.5))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (5 km/h)', 0.063); -- (3.8 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (6 km/h)', 0.076); -- (3.8 / (60 * (5/6)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (7 km/h)', 0.089); -- (3.8 / (60 * (5/7)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Caminar (8 km/h)', 0.101); -- (3.8 / (60 * (5/8)))

INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Bicicleta (5 km/h)', 0.142); -- (8.5 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Bicicleta (10 km/h)', 0.285); -- (8.5 / (60 / 2))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Bicicleta (15 km/h)', 0.428); -- (8.5 / (60 / (2/3)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Bicicleta (20 km/h)', 0.57); -- (8.5 / (60 / (2/4)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Bicicleta (25 km/h)', 0.713); -- (8.5 / (60 / (2/5)))
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Bicicleta (30 km/h)', 0.855); -- (8.5 / (60 / (2/6)))

INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Nadar (crawl, vigoroso)', 0.2167); -- (13.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Levantar pesas (intenso)', 0.1); -- (6.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Aeróbicos (alto impacto)', 0.1217); -- (7.3 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Elíptica (moderado)', 0.125); -- (7.5 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Saltar la cuerda (rápido)', 0.2); -- (12.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Yoga', 0.05); -- (3.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Pilates', 0.0667); -- (4.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Remo (moderado)', 0.1333); -- (8.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Senderismo', 0.1083); -- (6.5 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Escalada', 0.1667); -- (10.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Boxeo (saco de boxeo)', 0.1167); -- (7.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Baile (salsa, moderado)', 0.1); -- (6.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Fútbol', 0.1333); -- (8.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Baloncesto', 0.125); -- (7.5 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Tenis', 0.1167); -- (7.0 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Ciclismo de montaña', 0.1583); -- (9.5 / 60)
INSERT INTO Ejercicio (nombre, caloriasQuemadas) VALUES ('Esquí (fondo, moderado)', 0.15); -- (9.0 / 60)